# Generated by Django 5.0.2 on 2024-02-27 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_shop", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[("1", "Обычная доставка"), ("2", "Экспресс-доставка")],
                        default="1",
                        max_length=2,
                        verbose_name="способ доставки",
                    ),
                ),
                ("city", models.CharField(max_length=50, verbose_name="город")),
                ("address", models.CharField(max_length=1000, verbose_name="адрес")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("1", "Онлайн картой"),
                            ("2", "Онлайн со случайного чужого счёта"),
                        ],
                        default="1",
                        max_length=2,
                        verbose_name="способ оплаты",
                    ),
                ),
                (
                    "order_number",
                    models.IntegerField(blank=True, verbose_name="номер заказа"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("1", "не оплачен"), ("2", "оплачен")],
                        default="1",
                        max_length=2,
                        verbose_name="статус оплаты",
                    ),
                ),
                (
                    "commentary",
                    models.TextField(
                        blank=True, max_length=1000, verbose_name="комментарии к заказу"
                    ),
                ),
                (
                    "date_order",
                    models.DateTimeField(auto_now_add=True, verbose_name="дата заказа"),
                ),
                (
                    "error_text",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="текст ошибки"
                    ),
                ),
                (
                    "sum_order",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="сумма заказа",
                    ),
                ),
                (
                    "products_order",
                    models.ManyToManyField(
                        blank=True,
                        related_name="orders_product",
                        to="app_shop.product",
                        verbose_name="продукты заказа",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "заказ",
                "verbose_name_plural": "заказы",
            },
        ),
        migrations.CreateModel(
            name="ProductOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count",
                    models.IntegerField(default=0, verbose_name="количество товара"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_order.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_shop.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                related_name="orders",
                through="app_order.ProductOrder",
                to="app_shop.product",
            ),
        ),
    ]
