# Generated by Django 5.0.2 on 2024-03-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_order", "0002_remove_order_products_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(
                choices=[
                    ("ordinary", "Обычная доставка"),
                    ("express", "Экспресс-доставка"),
                ],
                default="ordinary",
                max_length=10,
                verbose_name="способ доставки",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("online", "Онлайн картой"),
                    ("someone", "Онлайн со случайного чужого счёта"),
                ],
                default="online",
                max_length=10,
                verbose_name="способ оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[(True, "не оплачен"), (False, "оплачен")],
                default=True,
                max_length=10,
                verbose_name="статус оплаты",
            ),
        ),
    ]
