# Generated by Django 5.0.2 on 2024-03-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_order", "0003_alter_order_delivery_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productorder",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=10,
                verbose_name="стоимость товара",
            ),
            preserve_default=False,
        ),
    ]
