# Generated by Django 5.0.2 on 2024-03-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_order", "0004_productorder_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("True", "не оплачен"), ("False", "оплачен")],
                default="True",
                max_length=10,
                verbose_name="статус оплаты",
            ),
        ),
    ]
