# Generated by Django 5.0.2 on 2024-03-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_order", "0005_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_delete",
            field=models.BooleanField(default=False),
        ),
    ]
