# Generated by Django 5.0.2 on 2024-02-27 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=1000,
                        verbose_name="название категории",
                    ),
                ),
                (
                    "active_category",
                    models.CharField(
                        blank=True,
                        choices=[("1", "active"), ("2", "inactive")],
                        default="1",
                        max_length=1,
                        verbose_name="автивность категории",
                    ),
                ),
                (
                    "file_icon",
                    models.FileField(
                        null=True, upload_to="files_icon/", verbose_name="файл иконки"
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=1000, verbose_name="название товара"
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=10000, verbose_name="описание товара"),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="цена товара",
                    ),
                ),
                (
                    "count_reviews",
                    models.IntegerField(default=0, verbose_name="количество отзывов"),
                ),
                (
                    "limited_edition",
                    models.BooleanField(verbose_name="ограниченный тираж"),
                ),
                ("count_goods", models.IntegerField(verbose_name="количество товара")),
                (
                    "free_delivery",
                    models.BooleanField(
                        default=False, verbose_name="бесплатная доставка"
                    ),
                ),
                (
                    "number_of_purchases",
                    models.IntegerField(
                        default=0, verbose_name="количество покупок товара"
                    ),
                ),
                (
                    "active_product",
                    models.BooleanField(verbose_name="активность товара"),
                ),
                (
                    "date_product",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата поступления товара"
                    ),
                ),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
                "ordering": ["name", "number_of_purchases"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=1000, verbose_name="название тега"),
                ),
            ],
            options={
                "verbose_name": "тег",
                "verbose_name_plural": "теги",
            },
        ),
        migrations.CreateModel(
            name="FileProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "files",
                    models.FileField(upload_to="files_goods/", verbose_name="файл"),
                ),
                (
                    "product_file",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_products",
                        to="app_shop.product",
                        verbose_name="продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "файл продукта",
                "verbose_name_plural": "файлы продукта",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_user",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="имя пользователя"
                    ),
                ),
                (
                    "text_comment",
                    models.TextField(
                        max_length=10000, verbose_name="текст комментария"
                    ),
                ),
                (
                    "date_comment",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата комментария"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_comments",
                        to="app_shop.product",
                        verbose_name="продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "комментарий",
                "verbose_name_plural": "комментарии",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="app_shop.tag"
            ),
        ),
    ]
