# Generated by Django 5.0.2 on 2024-02-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="file_icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="files_icon/",
                verbose_name="файл иконки",
            ),
        ),
    ]
