# Generated by Django 5.0.2 on 2024-02-27 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_shop", "0002_alter_category_file_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="category_products",
                to="app_shop.category",
                verbose_name="категория",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tags_products", to="app_shop.tag"
            ),
        ),
    ]
