# Generated by Django 5.0.2 on 2024-03-06 18:18

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_shop", "0003_product_category_alter_product_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="category_products",
                to="app_shop.category",
                verbose_name="категория",
            ),
        ),
    ]
