# Generated by Django 5.0.2 on 2024-03-06 18:36

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_shop", "0005_category_level_category_lft_category_rght_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="app_shop.category",
                verbose_name="родительская категория",
            ),
        ),
    ]
