# Generated by Django 5.0.2 on 2024-03-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_shop", "0006_category_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_delete",
            field=models.BooleanField(default=False),
        ),
    ]
